### ISSUE TITLE
Feature request: Home Assistant integration.

### ISSUE THREAD

**Issue by N1co93** [vigonotion/pygti#28]
Hello,

I just discovered your project and thought it would be great if there would be an integration for HA.

Is it maybe possible that you write an integration for HA? 
I think I can't help yout with it, because I have no programming experience. Maybe I can assistant during tests or something else.

Thank you in advance.

Greetings from Hamburg.

**Comment by vigonotion** [comment]
Hey, the Home Assistant integration is already finished, it's just awaiting review: https://github.com/home-assistant/core/pull/31564
If you already want to use it, you can check out that branch and copy the `hvv_departures` folder to your custom components folder. Tell me if you need help with that. You can setup the integration via the UI

**Comment by chronoB** [comment]
@vigonotion started this project for this reason so there should be something out there. ;)
@vigonotion can you guide the way?

**Comment by N1co93** [comment]
@vigonotion 
Thank you for your work on this integration. I've waited for such integration a long time . Just copied the files and everything is working fine. 

Hopefully more people are using this integration and HVV/Geofox are going to simplify the process to get the api credentials.

@chronoB 
Here is a short guide. Maybe there is a better way, but thats how I've done it:

1. Download the ZIP-file from this page https://github.com/vigonotion/home-assistant/tree/vi/hvv
2. Copy the folder from the zip-file "homeassistant/components/hvv_departures" to your local custom_components folder. 
3.  Restart HA and you are ready to go.
