### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mweinelt** [vigonotion/pygti#71]
Hi,

I noticed you specify two different licenses for this project. Can you clarfiy which one applies?

https://github.com/vigonotion/pygti/blob/fab9b6739b27d9ccce62d601225380da6f180968/LICENSE.md#L1-L3

https://github.com/vigonotion/pygti/blob/fab9b6739b27d9ccce62d601225380da6f180968/setup.py#L110

**Comment by vigonotion** [comment]
What else do you need? Just a new version on pypi or actually a version bump on HA?

**Comment by mweinelt** [comment]
I personally don't really need anything more than the clarification. Thank you.
